# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
# here search kind: HorizontalPodAutoscaler - u get 3 yaml but last yaml is this given below


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
